#!/usr/bin/env bash

#dpkg-query --show --showformat='${Installed-Size}\t${Package}\n' | sort -rh | awk '{printf "\033[1;33m%s\033[34m Mb \033[36m%s\033[0m\n", $1,$2}'

strd_file=$HOME
crtd_tmp='.SiS_success'

dpkg-query --show --showformat='${Installed-Size} ${Package} ${source}\n' | sort -rh| awk -v dir_="$strd_file" -v file_="$crtd_tmp" '{printf "\t%.2f\t\t#auto_created_by_sispack\n",$1/1024>dir_"/"file_} {printf " \033[1;33;40m%.2f\033[35m Mb\033[0;1m  \033[36m%s\033[0m\t%s\n", $1/1024,$2,$3}' && awk '{split($1,a,","); sum += a[1]} END {print "\033[1m-------------------------------\n"sum" MB ===> " sum/1024" GB\n-------------------------------\033[0m"}' $strd_file/$crtd_tmp
