#!/usr/bin/env bash

#dpkg-query --show --showformat='${Installed-Size}\t${Package}\n' | sort -rh | awk '{printf "\033[1;33m%s\033[34m Mb \033[36m%s\033[0m\n", $1,$2}'

strd_file=$HOME
crtd_tmp='.SiS_success'

dpkg-query --show --showformat='${Installed-Size} ${Package} ${source}\n' | sort -rh| awk -v dir_="$strd_file" -v file_="$crtd_tmp" '{printf "\t%.2f\t\t#auto_created_by_sispack\n",$1/1024>dir_"/"file_} {printf " \033[1;33;40m%.2f\033[35m Mb\033[0;1m  \033[36m%s\033[0m\t%s\n", $1/1024,$2,$3}' && awk '{split($1,a,","); sum += a[1]} END {print "\033[1m-------------------------------\n"sum" MB ===> " sum/1024" GB\n-------------------------------\033[0m"}' $strd_file/$crtd_tmp





#....[reserved].........
#
#
: ' -f, --showformat=format
              This option is used to specify the format of the output
              --show will produce (short option since dpkg 1.13.1).  The
              format is a string that will be output for each package
              listed.

              In the format string, “\” introduces escapes:

                  \n  newline
                  \r  carriage return
                  \t  tab

              “\” before any other character suppresses any special
              meaning of the following character, which is useful for
              “\” and “$”.

              Package information can be included by inserting variable
              references to package fields using the syntax
              “${field[;width]}”. Fields are printed right-aligned
              unless the width is negative in which case left alignment
              will be used. The following fields are recognized but they
              are not necessarily available in the status file (only
              internal fields or fields stored in the binary package end
              up in it):

                  Architecture
                  Bugs
                  Conffiles (internal)
                  Config-Version (internal)
                  Conflicts
                  Breaks
                  Depends
                  Description
                  Enhances
                  Essential
                  Filename (internal, front-end related)
                  Homepage
                  Installed-Size
                  MD5sum (internal, front-end related)
                  MSDOS-Filename (internal, front-end related)
                  Maintainer
                  Origin
                  Package
                  Pre-Depends
                  Priority
                  Provides
                  Recommends
                  Replaces
                  Revision (obsolete)
                  Section
                  Size (internal, front-end related)
                  Source
                  Status (internal)
                  Suggests
                  Tag (usually not in .deb but in repository Packages files)
                  Triggers-Awaited (internal)
                  Triggers-Pending (internal)
                  Version '
#this shows installed-file-size in kb. 
#dpkg-query --show --showformat='${Installed-Size}\t${Package}\n' | sort -rh | awk '{printf "\033[1;33m%s\033[34m Mb \033[36m%s\033[0m\n", $1,$2}'

#calculate whole size then put total size at last.
#   > file autocreated "SiS_success"
#   > showing in MB
#   > grand total in GB
# dpkg-query --show --showformat='${Installed-Size}\t${Package}\n' | sort -rh| awk '{printf "%.2f\n",$1/1024"\n">"success.txt"} {printf "\033[1;33m%.5g\033[34m Mb \033[36m%s\033[0m\n", $1/1024,$2}' && awk '{split($1,a,","); sum += a[1]} END {print sum}' success.txt
#----------------------------------------------
#R_.1
#dpkg-query --show --showformat='${Installed-Size}\t${Package}\n' | sort -rh | awk '{printf "\033[1;33m%.5g\033[34m Mb \033[36m%s\033[0m\n", $1/1024,$2}'

#R_.2
#dpkg-query --show --showformat='${Installed-Size}\t${Package}\n' | sort -rh| awk '{printf "%.3g %s\n",$1/1024,$2}{print $1/1024>".sis_.txt"}'

#R_.3
#see_installed-size|awk '{print $1>"hl.txt"}'
#awk '{split($1,a,","); sum += a[1]} END {print sum}' success.txt
#see | awk '{split($1,a,","); sum += a[1]} END {print sum}'


#R_.4 [in_USED]----------

#strd_file=$HOME
#crtd_tmp='.SiS_success'
#dpkg-query --show --showformat='${Installed-Size}\t${Package}\n' | sort -rh| awk -v dir_="$strd_file" -v file_="$crtd_tmp" '{printf "\t%.2f\t\t#auto_created_by_sispack\n",$1/1024>dir_"/"file_} {printf " \033[1;33;40m%.2f\033[35m Mb\033[0;1m  \033[36m%s\033[0m\n", $1/1024,$2}' && awk '{split($1,a,","); sum += a[1]} END {print "\033[1m-------------------------------\n"sum" MB ===> " sum/1024" GB\n-------------------------------\033[0m"}' $strd_file/$crtd_tmp

